version: '3.9'

services:
  aws:
    container_name: aws
    hostname: aws
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    expose:
      - 4566
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: exemplo
      AWS_SECRET_ACCESS_KEY: exemplo
    networks:
      - default
    
      
networks:
  default:
    driver: bridge
